#WEB SCRAPING – ASSIGNMENT 2

Internship ID - DS2402

Submitted by - Geetanjali Joshi

In [55]:
!pip install selenium

Requirement already satisfied: selenium in ./anaconda3/lib/python3.10/site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in ./anaconda3/lib/python3.10/site-packages (from selenium) (1.26.14)
Requirement already satisfied: typing_extensions>=4.9.0 in ./anaconda3/lib/python3.10/site-packages (from selenium) (4.10.0)
Requirement already satisfied: trio~=0.17 in ./anaconda3/lib/python3.10/site-packages (from selenium) (0.25.0)
Requirement already satisfied: certifi>=2021.10.8 in ./anaconda3/lib/python3.10/site-packages (from selenium) (2023.5.7)
Requirement already satisfied: trio-websocket~=0.9 in ./anaconda3/lib/python3.10/site-packages (from selenium) (0.11.1)
Requirement already satisfied: attrs>=23.2.0 in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: exceptiongroup in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: sniffio>=1.3.0 in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in ./anaconda3/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in ./anaconda3/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in ./anaconda3/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [56]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [57]:
driver = webdriver.Chrome()

Q1. You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company name, experience required.
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs

In [58]:
driver.get("https://www.naukri.com/")

In [59]:
# entering designation 

designation = driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Scientist')

In [60]:
# enter location 

location = driver.find_element(By.XPATH,"/html/body/div[1]/div[7]/div/div/div[5]/div/div/div/div[1]/div/input")
location.send_keys('Delhi/NCR')

In [61]:
# search bar 

search = designation = driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [62]:
job_title =[]
job_location = []
company_name = []
experience_required = []

In [63]:
# scarping for job title 

title_tags = driver.find_elements(By.XPATH, '//a[@class="title "]')
for i in title_tags[:10]:
    title=i.text
    job_title.append(title)

In [64]:
# scraping for location
location_tags = driver.find_elements(By.XPATH,'//span[@class="locWdth"]')
for i in location_tags[:10]:
    location=i.text
    job_location.append(location)

In [65]:
# scraping for company name
company_tags = driver.find_elements(By.XPATH,'//a[@class=" comp-name mw-25"]')
for i in company_tags[:10]:
    company=i.text
    company_name.append(company)

In [66]:
# scraping for experience tags
experience_tags = driver.find_elements(By.XPATH,'//span[@class="expwdth"]')
for i in experience_tags[:10]:
    experience=i.text
    experience_required.append(experience)

In [67]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

10 10 10 10

In [68]:
import pandas as pd
df = pd.DataFrame({'Title': job_title,'Location':job_location,'Company_name':company_name,'Experience':experience_required})
df.head()

,Title,Location,Company_name,Experience
0,"Senior Data Scientist, Reporting","Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Coursera,6-7 Yrs
1,"Data Scientist, Marketing","Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Coursera,4-6 Yrs
2,Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",Ford,3-6 Yrs
3,Lead Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",Ford,2-6 Yrs
4,Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",Ford,5-6 Yrs

Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

In [82]:
!pip install selenium

Requirement already satisfied: selenium in ./anaconda3/lib/python3.10/site-packages (4.19.0)
Requirement already satisfied: trio~=0.17 in ./anaconda3/lib/python3.10/site-packages (from selenium) (0.25.0)
Requirement already satisfied: typing_extensions>=4.9.0 in ./anaconda3/lib/python3.10/site-packages (from selenium) (4.10.0)
Requirement already satisfied: trio-websocket~=0.9 in ./anaconda3/lib/python3.10/site-packages (from selenium) (0.11.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in ./anaconda3/lib/python3.10/site-packages (from selenium) (1.26.14)
Requirement already satisfied: certifi>=2021.10.8 in ./anaconda3/lib/python3.10/site-packages (from selenium) (2023.5.7)
Requirement already satisfied: sortedcontainers in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: exceptiongroup in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: attrs>=23.2.0 in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sniffio>=1.3.0 in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: outcome in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: wsproto>=0.14 in ./anaconda3/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in ./anaconda3/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in ./anaconda3/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [83]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [88]:
driver = webdriver.Chrome()

In [89]:
driver.get("https://www.shine.com/")

In [90]:
# entering designation 

skill = driver.find_element(By.XPATH,"/html/body/div/div[2]/div/div/div[1]/div[1]/div/div[2]/div/div/form/div/div[1]/ul/li[1]/div/input")
skill.send_keys('Data Analyst')

In [91]:
# enter location 

location_b = driver.find_element(By.XPATH,"/html/body/div/div[2]/div/div/div[1]/div[1]/div/div[2]/div/div/form/div/div[1]/ul/li[2]/div/input")
location_b.send_keys('Bangalore')

In [93]:
# search bar 

search1 = skill = driver.find_element(By.XPATH," /html/body/div/div[2]/div/div/div[1]/div[1]/div/div[2]/div/div/form/div/div[2]/div/button")
search1.click()

In [94]:
job_title =[]
job_location = []
company_name = []
experience_required = []

In [95]:
# scarping for job title 

title_tags = driver.find_elements(By.XPATH, '//strong[@class="jobCard_pReplaceH2__xWmHg"]')
for i in title_tags[:10]:
    title=i.text
    job_title.append(title)

In [96]:
# scraping for location/
location_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in location_tags[:10]:
    location=i.text
    job_location.append(location)

In [97]:
# scraping for company name
company_tags = driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
for i in company_tags[:10]:
    company=i.text
    company_name.append(company)

In [98]:
# scraping for experience tags
experience_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
for i in experience_tags[:10]:
    experience=i.text
    experience_required.append(experience)

In [99]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

10 10 10 10

In [100]:
import pandas as pd
df = pd.DataFrame({'Title': job_title,'Location':job_location,'Company_name':company_name,'Experience':experience_required})
df.head()

,Title,Location,Company_name,Experience
0,Data Analyst Recruitment,Bangalore\n+12,radhika enterprises,0 to 4 Yrs
1,Data Analyst Recruitment,Bangalore\n+12,radhika enterprises,0 to 4 Yrs
2,"Data Analyst (Power BI, Python, SQL)- Internal...",Bangalore,talent leads hr solutions pvt ltd,3 to 8 Yrs
3,Data Analyst,Bangalore\n+12,millennium babycares private limite...,9 to 14 Yrs
4,Clinical Data Analyst,Bangalore\n+6,techno endura,0 to 1 Yr

Q3.Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link:

As shown in the above page you have to scrape the tick marked attributes. These are:
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100reviews.

In [102]:
!pip install selenium

Requirement already satisfied: selenium in ./anaconda3/lib/python3.10/site-packages (4.19.0)
Requirement already satisfied: trio~=0.17 in ./anaconda3/lib/python3.10/site-packages (from selenium) (0.25.0)
Requirement already satisfied: certifi>=2021.10.8 in ./anaconda3/lib/python3.10/site-packages (from selenium) (2023.5.7)
Requirement already satisfied: typing_extensions>=4.9.0 in ./anaconda3/lib/python3.10/site-packages (from selenium) (4.10.0)
Requirement already satisfied: trio-websocket~=0.9 in ./anaconda3/lib/python3.10/site-packages (from selenium) (0.11.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in ./anaconda3/lib/python3.10/site-packages (from selenium) (1.26.14)
Requirement already satisfied: outcome in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: exceptiongroup in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=23.2.0 in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: idna in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: sortedcontainers in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio>=1.3.0 in ./anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in ./anaconda3/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in ./anaconda3/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in ./anaconda3/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [103]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [115]:
driver = webdriver.Chrome()

In [116]:
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&marketplace=FLIPKART")

In [111]:
product_name =[]
rating =[]
review_summary = []
full_review = []

In [117]:
# search

search = driver.find_element(By.XPATH,"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input")
search.send_keys('iphone 11')

In [118]:
# search bar 

search2 = search = driver.find_element(By.XPATH,"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button/svg/g/path[2]")
search2.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button/svg/g/path[2]"}
  (Session info: chrome=123.0.6312.107); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001013784a4 chromedriver + 4326564
1   chromedriver                        0x000000010137096c chromedriver + 4295020
2   chromedriver                        0x0000000100f9c088 chromedriver + 278664
3   chromedriver                        0x0000000100fdea80 chromedriver + 551552
4   chromedriver                        0x00000001010174f8 chromedriver + 783608
5   chromedriver                        0x0000000100fd34e4 chromedriver + 505060
6   chromedriver                        0x0000000100fd3f5c chromedriver + 507740
7   chromedriver                        0x000000010133ba40 chromedriver + 4078144
8   chromedriver                        0x00000001013407f8 chromedriver + 4098040
9   chromedriver                        0x00000001013225e4 chromedriver + 3974628
10  chromedriver                        0x0000000101341110 chromedriver + 4100368
11  chromedriver                        0x0000000101313bd4 chromedriver + 3914708
12  chromedriver                        0x0000000101361718 chromedriver + 4232984
13  chromedriver                        0x0000000101361894 chromedriver + 4233364
14  chromedriver                        0x00000001013705e0 chromedriver + 4294112
15  libsystem_pthread.dylib             0x0000000184d46f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000184d41d34 thread_start + 8

In [ ]:
# scraping rating for first 100 products

product_tag = driver.find_elements(By.XPATH, '//strong[@class="jobCard_pReplaceH2__xWmHg"]')
for i in product_tags[:10]:
    product=i.text
    products.append(product)

In [ ]:
# entering designation 

skill = driver.find_element(By.XPATH,"/html/body/div/div[2]/div/div/div[1]/div[1]/div/div[2]/div/div/form/div/div[1]/ul/li[1]/div/input")
skill.send_keys('Data Analyst')

Q4.Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.
You have to scrape 3 attributes of each sneaker:
1. Brand
2. Product Description

In [159]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

#set webdriver
driver = webdriver.Chrome()

# enter url flipkart.com
driver.get("https://www.flipkart.com/")

# Find the search bar and enter "sneakers"
search_sneakers = driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input")
search_sneakers.send_keys('Sneakers')
search = search_sneakers = driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/button")
search.click()

# Initialize lists to store scraped data
brands = []
descriptions = []
prices = []

# Loop through the first 100 sneakers
while len(brands) < 100:
    # Find all sneakers on the page
    sneaker_cards = driver.find_elements(By.XPATH, "//div[@class='_2WkVRV']")
    for card in sneaker_cards:
        # Extract brand
        brand = card.find_element(By.XPATH, '//div[@class="_2WkVRV"]').text
        brands.append(brand)
        
        # Extract description
        description = card.find_element(By.XPATH,'//a[@class="IRpwTa"]').text
        descriptions.append(description)
        
        # Extract price
        try:
            price = card.find_element(By.XPATH,'//a[@class="_3bPFwb"]').text
        except:
            price = "Price not available"
        prices.append(price)
        
        # Check if we've scraped 100 sneakers
        if len(brands) == 100:
            break

    # If there are more pages, navigate to the next page
    try:
        next_button = driver.find_element(By.XPATH, '//a[@class="_1LKTO3"]')
        next_button.click()
        time.sleep(2)  # Wait for the page to load
    except:
        break  # Exit loop if there are no more pages

# Close the WebDriver
driver.quit()

# Print the scraped data
for i in range(100):
    print("Sneaker", i+1)
    print("Brand:", brands[i])
    print("Description:", descriptions[i])
    print("Price:", prices[i])
    print()

Sneaker 1
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 2
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 3
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 4
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 5
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 6
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 7
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 8
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 9
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 10
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 11
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 12
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 13
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 14
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 15
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 16
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 17
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 18
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 19
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 20
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 21
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 22
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 23
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 24
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 25
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 26
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 27
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 28
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 29
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 30
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 31
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 32
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 33
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 34
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 35
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 36
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 37
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 38
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 39
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 40
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 41
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 42
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 43
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 44
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 45
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 46
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 47
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 48
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 49
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 50
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 51
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 52
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 53
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 54
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 55
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 56
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 57
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 58
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 59
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 60
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 61
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 62
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 63
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 64
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 65
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 66
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 67
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 68
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 69
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 70
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 71
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 72
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 73
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 74
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 75
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 76
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 77
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 78
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 79
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 80
Brand: ADIDAS
Description: Advantage Base Sneakers For Women
Price: ₹3,429₹6,59948% off
Free delivery

Sneaker 81
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 82
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 83
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 84
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 85
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 86
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 87
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 88
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 89
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 90
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 91
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 92
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 93
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 94
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 95
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 96
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 97
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 98
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 99
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

Sneaker 100
Brand: RED TAPE
Description: Casual Sneaker Shoes for Women | Soft Cushioned Insole,...
Price: ₹2,189₹7,29970% off
Free delivery

# end of solution 4

Q5.Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon. Then set CPU Type filter to “Intel Core i7” as shown in the below image:
After setting the filters scrape first 10 laptops data. You have to scrape 3 attributes for each laptop:
1. Title
2. Ratings
3. Price

In [161]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# set up webdriver
driver = webdriver.Chrome()

# login to amazon
driver.get("https://www.amazon.in/")

In [162]:
# search for Laptop
search_bar = driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input")
search_bar.send_keys("Laptop")

In [163]:
search = search_bar = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input")
search.click()

In [165]:
cpu = cpu_filter = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[7]/div[19]/div/ul/span[9]/li/span/a/span')
cpu.click()

In [166]:
# Initialize lists to store scraped data
titles = []
ratings = []
prices = []

In [170]:
# Find the first 10 laptop listings
laptops = driver.find_elements(By.XPATH, '/html/body/div[1]/div[1]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[3]/div/div/ul/span[2]/li[6]/span/a/span')[:10]

In [172]:
for laptop in laptops:
    # Extract title
    title_element = laptop.find_element(By.XPATH, '//span[@class="a-size-medium a-color-base a-text-normal"]')
    title = title_element.text
    titles.append(title)
    
    # Extract rating
    try:
        rating_element = laptop.find_element(By.XPATH, '//[@a-icon a-icon-star-small a-star-small-4-5 aok-align-bottom]')
        rating = rating_element.get_attribute("innerHTML")
        ratings.append(rating)
    except:
        ratings.append("Rating not available")
    
    # Extract price
    try:
        price_element = laptop.find_element(By.XPATH,'//[@a-price-whole]')
        price = price_element.text
        prices.append(price)
    except:
        prices.append("Price not available")

for i in range(10):
    print("Laptop", i+1)
    print("Title:", titles[i])
    print("Rating:", ratings[i])
    print("Price:", prices[i])
    print()

# Close the WebDriver
driver.quit()

Laptop 1
Title: MSI Modern 14, Intel 12th Gen. i7-1255U, 36CM FHD 60Hz Laptop (16GB/512GB NVMe SSD/Windows 11 Home/Intel Iris Xe Graphics/Classic Black/1.4Kg), C12M-459IN
Rating: Rating not available
Price: Price not available

Laptop 2

IndexError: list index out of range

# end of solution 5

Q6: Write a python program to scrape data for Top 1000 Quotes of All Time.
The above task will be done in following steps:
1. First get the webpagehttps://www.azquotes.com/
2. Click on Top Quote
3. Than scrap a) Quote b) Author c) Type Of Quotes

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

In [187]:
driver = webdriver.Chrome()

In [199]:
driver.get("https://www.azquotes.com/top_quotes.html")

In [201]:
# click on topquote
top_quote= driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[1]/span[2]')
top_quote.click()

In [202]:
# Initialize lists to store scraped data
quotes = []
authors = []
types = []

In [207]:
# extracting quotes
quote_tags = driver.find_elements(By.XPATH, '//a[@class="title"]')
for i in quote_tags:
    quote =i.text
    quotes.append(quote)

In [208]:
# extracting authors
author_tags = driver.find_elements(By.XPATH, '//div[@class="author"]')
for i in author_tags:
    author =i.text
    authors.append(author)

In [209]:
# extracting types
type_tags = driver.find_elements(By.XPATH, '//div[@class="tags"]')
for i in type_tags:
    type=i.text
    types.append(type)

In [213]:
for i in range(1000):
    print("quotes", i+1)
    print("quotes_title", quotes[i])
    print("Authors", authors[i])
    print("Type", types[i])
    print("")
    print("")

quotes 1
quotes_title The essence of strategy is choosing what not to do.
Authors Michael Porter
Type Essence, Deep Thought, Transcendentalism


quotes 2
quotes_title One cannot and must not try to erase the past merely because it does not fit the present.
Authors Golda Meir
Type Inspiration, Past, Trying


quotes 3
quotes_title Patriotism means to stand by the country. It does not mean to stand by the president.
Authors Theodore Roosevelt
Type Country, Peace, War


quotes 4
quotes_title Death is something inevitable. When a man has done what he considers to be his duty to his people and his country, he can rest in peace. I believe I have made that effort and that is, therefore, why I will sleep for the eternity.
Authors Nelson Mandela
Type Inspirational, Motivational, Death


quotes 5
quotes_title You have to love a nation that celebrates its independence every July 4, not with a parade of guns, tanks, and soldiers who file by the White House in a show of strength and muscle, but with family picnics where kids throw Frisbees, the potato salad gets iffy, and the flies die from happiness. You may think you have overeaten, but it is patriotism.
Authors Erma Bombeck
Type 4th Of July, Food, Patriotic


quotes 6
quotes_title Be more concerned with your character than your reputation, because your character is what you really are, while your reputation is merely what others think you are.
Authors John Wooden
Type Inspirational, Success, Basketball


quotes 7
quotes_title Weak people revenge. Strong people forgive. Intelligent People Ignore.
Authors Albert Einstein
Type Strong, Revenge, Intelligent


quotes 8
quotes_title A mind is like a parachute. It doesn't work if it is not open.
Authors Frank Zappa
Type Inspirational, Teacher, Religious


quotes 9
quotes_title Never be afraid to raise your voice for honesty and truth and compassion against injustice and lying and greed. If people all over the world...would do this, it would change the earth.
Authors William Faulkner
Type Truth, Honesty, Lying


quotes 10
quotes_title There are three kinds of men. The one that learns by reading. The few who learn by observation. The rest of them have to pee on the electric fence for themselves.
Authors Will Rogers
Type Funny, Reading, Learning


quotes 11
quotes_title A strong nation, like a strong person, can afford to be gentle, firm, thoughtful, and restrained. It can afford to extend a helping hand to others. It's a weak nation, like a weak person, that must behave with bluster and boasting and rashness and other signs of insecurity.
Authors Jimmy Carter
Type Strong, Thoughtful, Compassion


quotes 12
quotes_title The difference between stupidity and genius is that genius has its limits.
Authors Albert Einstein
Type Love, Funny, Life


quotes 13
quotes_title We the people are the rightful masters of both Congress and the courts, not to overthrow the Constitution but to overthrow the men who pervert the Constitution.
Authors Abraham Lincoln
Type Freedom, Men, Democracies Have


quotes 14
quotes_title With or without religion, you would have good people doing good things and evil people doing evil things. But for good people to do evil things, that takes religion.
Authors Steven Weinberg
Type God, Religious, Atheist


quotes 15
quotes_title Human kindness has never weakened the stamina or softened the fiber of a free people. A nation does not have to be cruel to be tough.
Authors Franklin D. Roosevelt
Type Respect, Kindness, Character


quotes 16
quotes_title A person who never made a mistake never tried anything new.
Authors Albert Einstein
Type Inspirational, Motivational, Change


quotes 17
quotes_title My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style
Authors Maya Angelou
Type Inspirational, Life, Inspiring


quotes 18
quotes_title Life is short, Break the Rules. Forgive quickly, Kiss slowly. Love truly. Laugh uncontrollably And never regret ANYTHING That makes you smile.
Authors Mark Twain
Type Love, Inspirational, Life


quotes 19
quotes_title This country will not be a good place for any of us to live in unless we make it a good place for all of us to live in.
Authors Theodore Roosevelt
Type Inspiring, Country, 4th Of July


quotes 20
quotes_title In a world filled with hate, we must still dare to hope. In a world filled with anger, we must still dare to comfort. In a world filled with despair, we must still dare to dream. And in a world filled with distrust, we must still dare to believe.
Authors Michael Jackson
Type Inspirational, Dream, Hate


quotes 21
quotes_title Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.
Authors Martin Luther King, Jr.
Type Love, Inspirational, Life


quotes 22
quotes_title To be a Christian means to forgive the inexcusable because God has forgiven the inexcusable in you.
Authors C. S. Lewis
Type Forgiveness, God, Christian


quotes 23
quotes_title A man who is good enough to shed his blood for the country is good enough to be given a square deal afterwards.
Authors Theodore Roosevelt
Type Country, Men, Squares


quotes 24
quotes_title Kindness is the language which the deaf can hear and the blind can see.
Authors Mark Twain
Type Inspirational, Relationship, Positive


quotes 25
quotes_title Most folks are as happy as they make up their minds to be.
Authors Abraham Lincoln
Type Inspirational, Motivational, Positive


quotes 26
quotes_title A happy marriage is the union of two good forgivers.
Authors Ruth Graham
Type Love, Friendship, Relationship


quotes 27
quotes_title I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.
Authors C. S. Lewis
Type Faith, God, Christian


quotes 28
quotes_title Politics is the art of looking for trouble, finding it everywhere, diagnosing it incorrectly and applying the wrong remedies.
Authors Groucho Marx
Type Art, Freedom, Political Will


quotes 29
quotes_title I believe in everything until it's disproved. So I believe in fairies, the myths, dragons. It all exists, even if it's in your mind. Who's to say that dreams and nightmares aren't as real as the here and now?
Authors John Lennon
Type Inspirational, Life, Faith


quotes 30
quotes_title At the end of your life, you will never regret not having passed one more test, not winning one more verdict or not closing one more deal. You will regret time not spent with a husband, a friend, a child, or a parent.
Authors Barbara Bush
Type Inspirational, Life, Meaningful


quotes 31
quotes_title I never think of the future - it comes soon enough.
Authors Albert Einstein
Type Happiness, Time, Clever


quotes 32
quotes_title Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.
Authors Francis Chan
Type Inspirational, Inspiring, Success


quotes 33
quotes_title Failure is simply the opportunity to begin again, this time more intelligently.
Authors Henry Ford
Type Love, Inspirational, Life


quotes 34
quotes_title Music expresses that which cannot be put into words.
Authors Victor Hugo
Type Music, Sound And Music, Musical Life


quotes 35
quotes_title Good actions are a guard against the blows of adversity.
Authors Abu Bakr
Type Adversity, Blow, Action


quotes 36
quotes_title Positive thinking will let you do everything better than negative thinking will.
Authors Zig Ziglar
Type Positive, Thinking Of You, Attitude


quotes 37
quotes_title You have enemies? Good. That means you've stood up for something, sometime in your life.
Authors Winston Churchill
Type Inspirational, Funny, Life


quotes 38
quotes_title You don't have to be great to start, but you have to start to be great
Authors Zig Ziglar
Type Inspirational, Life, Motivational


quotes 39
quotes_title Let every nation know, whether it wishes us well or ill, that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe to assure the survival and the success of liberty.
Authors John F. Kennedy
Type Inspirational, Memorial Day, Freedom


quotes 40
quotes_title If you want total security, go to prison. There you're fed, clothed, given medical care and so on. The only thing lacking... is freedom.
Authors Dwight D. Eisenhower
Type Freedom, Patriotic, Vaccines


quotes 41
quotes_title Socialism is a philosophy of failure, the creed of ignorance, and the gospel of envy, its inherent virtue is the equal sharing of misery.
Authors Winston Churchill
Type Philosophy, Ignorance, Democratic Socialism


quotes 42
quotes_title It is the supreme art of the teacher to awaken joy in creative expression and knowledge.
Authors Albert Einstein
Type Inspirational, Dance, Education


quotes 43
quotes_title Once you replace negative thoughts with positive ones, you'll start having positive results.
Authors Willie Nelson
Type Life, Change, Positive


quotes 44
quotes_title You build on failure. You use it as a stepping stone. Close the door on the past. You don't try to forget the mistakes, but you don't dwell on it. You don't let it have any of your energy, or any of your time, or any of your space.
Authors Johnny Cash
Type Life, Bullying, Mistake


quotes 45
quotes_title All my life through, the new sights of Nature made me rejoice like a child.
Authors Marie Curie
Type Life, Nature, Children


quotes 46
quotes_title I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.
Authors Maya Angelou
Type Inspirational, Life, Motivational


quotes 47
quotes_title Marriage is not a ritual or an end. It is a long, intricate, intimate dance together and nothing matters more than your own sense of balance and your choice of partner.
Authors Amy Bloom
Type Marriage, Love You, Long


quotes 48
quotes_title When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.
Authors Zig Ziglar
Type Inspirational, Motivational, Success


quotes 49
quotes_title Time you enjoy wasting, was not wasted.
Authors John Lennon
Type Love, Inspirational, Life


quotes 50
quotes_title The next time some academics tell you how important diversity is, ask how many Republicans there are in their sociology department.
Authors Thomas Sowell
Type Diversity, Important, Liberty


quotes 51
quotes_title Faith is not the belief that God will do what you want. It is the belief that God will do what is right.
Authors Max Lucado
Type Inspirational, God, Faith


quotes 52
quotes_title If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.
Authors Martin Luther King, Jr.
Type Inspirational, Motivational, Inspiring


quotes 53
quotes_title It is hard to imagine a more stupid or more dangerous way of making decisions than by putting those decisions in the hands of people who pay no price for being wrong.
Authors Thomas Sowell
Type Business, Stupid, Government


quotes 54
quotes_title I say that the most liberating thing about beauty is realizing that you are the beholder.
Authors Salma Hayek
Type Beauty, Love Yourself, Your Beautiful


quotes 55
quotes_title The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.
Authors Martin Luther King, Jr.
Type Inspirational, Life, Motivational


quotes 56
quotes_title The soldier, above all other people, prays for peace, for he must suffer and bear the deepest wounds and scars of war.
Authors Douglas MacArthur
Type Peace, Military, War


quotes 57
quotes_title A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. He does not set out to be a leader, but becomes one by the equality of his actions and the integrity of his intent.
Authors Douglas MacArthur
Type Inspirational, Leadership, Confidence


quotes 58
quotes_title I am a Soldier, I fight where I am told, and I win where I fight.
Authors George S. Patton
Type Motivational, Military, War


quotes 59
quotes_title Trying to do the Lord's work in your own strength is the most confusing, exhausting, and tedious of all work. But when you are filled with the Holy Spirit, then the ministry of Jesus just flows out of you.
Authors Corrie Ten Boom
Type Christian, Jesus, Confusing


quotes 60
quotes_title Sports for me is when a guy walks off the court, and you really can't tell whether he won or lost, when he carries himself with pride either way.
Authors Jim Courier
Type Inspirational, Success, Sports


quotes 61
quotes_title Expect the best. Prepare for the worst. Capitalize on what comes.
Authors Zig Ziglar
Type Inspirational, Motivational, Success


quotes 62
quotes_title I became insane, with long intervals of horrible sanity.
Authors Edgar Allan Poe
Type Inspirational, Life, Clever


quotes 63
quotes_title Failure is a detour, not a dead-end street.
Authors Zig Ziglar
Type Inspirational, Death, Failure


quotes 64
quotes_title I am not a product of my circumstances. I am a product of my decisions.
Authors Stephen Covey
Type Inspirational, Life, Motivational


quotes 65
quotes_title You can cut all the flowers but you cannot keep spring from coming.
Authors Pablo Neruda
Type Inspiring, Hope, Spring


quotes 66
quotes_title Life doesn't run away from nobody. Life runs at people.
Authors Joe Frazier
Type Motivational, Running, People


quotes 67
quotes_title In order to succeed, your desire for success should be greater than your fear of failure.
Authors Bill Cosby
Type Inspirational, Motivational, Positive


quotes 68
quotes_title It's difficult to think anything but pleasant thoughts while eating a homegrown tomato.
Authors Lewis Grizzard
Type Summer, Food, Garden


quotes 69
quotes_title Too many of us are not living our dreams because we are living our fears.
Authors Les Brown
Type Inspirational, Life, Motivational


quotes 70
quotes_title If the only prayer you ever say in your entire life is thank you, it will be enough.
Authors Meister Eckhart
Type Inspirational, Life, Thank You


quotes 71
quotes_title It's just a job. Grass grows, birds fly, waves pound the sand. I beat people up.
Authors Muhammad Ali
Type Funny, Sports, Jobs


quotes 72
quotes_title A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.
Authors John C. Maxwell
Type Being Strong, Wisdom, Stay Strong


quotes 73
quotes_title Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.
Authors Thomas A. Edison
Type Inspirational, Motivational, Positive


quotes 74
quotes_title It has been said, 'time heals all wounds.' I do not agree. The wounds remain. In time, the mind, protecting its sanity, covers them with scar tissue and the pain lessens. But it is never gone.
Authors Rose Kennedy
Type Time, Pain, Get Well


quotes 75
quotes_title This is one small step for a man, one giant leap for mankind.
Authors Neil Armstrong
Type Motivational, Positive, Moon


quotes 76
quotes_title I have held many things in my hands, and I have lost them all; but whatever I have placed in God's hands, that I still possess.
Authors Martin Luther
Type Life, God, Christian


quotes 77
quotes_title Welfare's purpose should be to eliminate, as far as possible, the need for its own existence.
Authors Ronald Reagan
Type President, Needs, Purpose


quotes 78
quotes_title Each time, before you intercede, be quiet first, and worship God in His glory. Think of what He can do, and how He delights to hear the prayers of His redeemed people. Think of your place and privilege in Christ, and expect great things!
Authors Andrew Murray
Type God, Faith, Christian


quotes 79
quotes_title Failure is not the opposite of success; it's part of success.
Authors Arianna Huffington
Type Women, Failure, Successful


quotes 80
quotes_title No one has ever become poor by giving.
Authors Anne Frank
Type Inspirational, Morning, Kindness


quotes 81
quotes_title It is not my ability, but my response to God’s ability, that counts.
Authors Corrie Ten Boom
Type Hiding Place, Ability, Baby Boom


quotes 82
quotes_title No one is born hating another person because of the color of his skin, or his background, or his religion. People must learn to hate, and if they can learn to hate, they can be taught to love, for love comes more naturally to the human heart than its opposite.
Authors Nelson Mandela
Type Love, Inspirational, Life


quotes 83
quotes_title No matter what people tell you, words and ideas can change the world.
Authors Robin Williams
Type Inspirational, Change, Philosophy


quotes 84
quotes_title A man should never neglect his family for business.
Authors Walt Disney
Type Inspirational, Family, Inspiring


quotes 85
quotes_title Those who dare to fail miserably can achieve greatly.
Authors John F. Kennedy
Type Inspirational, Success, Courage


quotes 86
quotes_title The two most important days in your life are the day you are born and the day you find out why.
Authors Mark Twain
Type Inspirational, Life, Motivational


quotes 87
quotes_title We must be global Christians with a global vision because our God is a global God.
Authors John Stott
Type Christian, Vision, Missionary


quotes 88
quotes_title With everything that has happened to you, you can either feel sorry for yourself or treat what has happened as a gift. Everything is either an opportunity to grow or an obstacle to keep you from growing. You get to choose.
Authors Wayne Dyer
Type Inspirational, Positive, Regret


quotes 89
quotes_title Don’t let the noise of others’ opinions drown out your own inner voice.
Authors Steve Jobs
Type Love, Inspirational, Life


quotes 90
quotes_title History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.
Authors Maya Angelou
Type Inspirational, Life, Encouragement


quotes 91
quotes_title How old would you be if you didn't know how old you are?
Authors Satchel Paige
Type Happy Birthday, Baseball, Fun


quotes 92
quotes_title Leadership is a privilege to better the lives of others. It is not an opportunity to satisfy personal greed.
Authors Mwai Kibaki
Type Leadership, Power, Opportunity


quotes 93
quotes_title If you have good thoughts they will shine out of your face like sunbeams and you will always look lovely.
Authors Roald Dahl
Type Inspirational, Life, Positive


quotes 94
quotes_title Never cut a tree down in the wintertime. Never make a negative decision in the low time. Never make your most important decisions when you are in your worst moods. Wait. Be patient. The storm will pass. The spring will come.
Authors Robert H. Schuller
Type Inspirational, Encouraging, Patience


quotes 95
quotes_title An optimist stays up until midnight to see the new year in. A pessimist stays up to make sure the old year leaves.
Authors Bill Vaughan
Type New Year, Fun, New Beginnings


quotes 96
quotes_title When the going gets weird, the weird turn pro.
Authors Hunter S. Thompson
Type Music, Sports, Hunting


quotes 97
quotes_title When a train goes through a tunnel and it gets dark, you don't throw away the ticket and jump off. You sit still and trust the engineer.
Authors Corrie Ten Boom
Type Trust, Encouraging, Uplifting


quotes 98
quotes_title If you think you are too small to make a difference, try sleeping with a mosquito.
Authors Dalai Lama
Type Inspirational, Funny, Change


quotes 99
quotes_title God doesn't require us to succeed, he only requires that you try.
Authors Mother Teresa
Type Success, God, Mother


quotes 100
quotes_title Change your thoughts and you change your world.
Authors Norman Vincent Peale
Type Inspirational, Motivational, Change


quotes 101

IndexError: list index out of range

In [214]:
driver.quit()

# end of solution 6

Q7: Write a python program to display list of respected former Prime Ministers of India (i.e. Name, Born-Dead, Term of office, Remarks) from https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1
scrap the mentioned data and make the DataFrame

In [219]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

In [224]:
driver = webdriver.Chrome()
url = "https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1"
driver.get(url)

In [225]:
# Find the table containing the list of Prime Ministers
table = driver.find_element(By.CLASS_NAME, "TableData")

In [227]:
# Initialize lists to store scraped data
names = []
born_dead = []
term_of_office = []
remarks = []

In [ ]:
# Loop through each row in the table
rows = table.find_elements(By.TAG_NAME, "tr")[1:]  # Skip the header row
for row in rows:
    # Extract data from each cell in the row
    cells = row.find_elements(By.TAG_NAME, "td")
    name = cells[0].text.strip()
    bd = cells[1].text.strip()
    to = cells[2].text.strip()
    remark = cells[3].text.strip()
    
    # Append data to lists
    names.append(name)
    born_dead.append(bd)
    term_of_office.append(to)
    remarks.append(remark)

# Create a DataFrame
data = {
    "Name": names,
    "Born-Dead": born_dead,
    "Term of Office": term_of_office,
    "Remarks": remarks
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

# Close the WebDriver
driver.quit()

In [234]:
driver.quit()

# end of solution 7

Q8: Write a python program to display list of 50 Most expensive cars in the world (i.e. Car name and Price) from https://www.motor1.com/
This task will be done in following steps:
1. First get the webpage https://www.motor1.com/
2. Then You have to type in the search bar ’50 most expensive cars’
3. Then click on 50 most expensive cars in the world..
4. Then scrap the mentioned data and make the dataframe.

In [229]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

In [263]:
driver = webdriver.Chrome()

In [264]:
driver.get("https://www.motor1.com/ ")

In [266]:
search_bar = driver.find_element(By.XPATH,"/html/body/div[9]/div[2]/div/div/div[3]/div/div/div/form/input")
search_bar.send_keys('most expensive cars in the world')

In [267]:
search = search_bar = driver.find_element(By.XPATH,"/html/body/div[9]/div[2]/div/div/div[3]/div/div/div/form/button[1]")
search.click()

In [268]:
most_expensive_cars = driver.find_element(By.XPATH,'/html/body/div[9]/div[9]/div/div[1]/div/div/div[3]/div')
most_expensive_cars.click()

In [269]:
# Initialize lists to store scraped data
car_names = []
price = []
description = []

In [270]:
# extracting car_names
car_tags = driver.find_elements(By.XPATH, '//h3[@class="subheader"]')
for i in car_tags:
    car =i.text
    car_names.append(car)

In [271]:
# extracting price
price_tags = driver.find_elements(By.XPATH, '/html/body/div[9]/div[7]/div[2]/div[1]/div[2]/div[1]/p[4]/strong')
for i in price_tags:
    p =i.text
    price.append(p)

In [277]:
# extracting description

description_tags = driver.find_elements(By.TAG_NAME, 'p')
for i in description_tags:
    describe =i.text
    description.append(describe)

WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=123.0.6312.107)
Stacktrace:
0   chromedriver                        0x0000000104ab04a4 chromedriver + 4326564
1   chromedriver                        0x0000000104aa896c chromedriver + 4295020
2   chromedriver                        0x00000001046d4088 chromedriver + 278664
3   chromedriver                        0x00000001046bcda4 chromedriver + 183716
4   chromedriver                        0x00000001046bcce0 chromedriver + 183520
5   chromedriver                        0x000000010474ec28 chromedriver + 781352
6   chromedriver                        0x000000010470b4e4 chromedriver + 505060
7   chromedriver                        0x000000010470bf5c chromedriver + 507740
8   chromedriver                        0x0000000104a73a40 chromedriver + 4078144
9   chromedriver                        0x0000000104a787f8 chromedriver + 4098040
10  chromedriver                        0x0000000104a5a5e4 chromedriver + 3974628
11  chromedriver                        0x0000000104a79110 chromedriver + 4100368
12  chromedriver                        0x0000000104a4bbd4 chromedriver + 3914708
13  chromedriver                        0x0000000104a99718 chromedriver + 4232984
14  chromedriver                        0x0000000104a99894 chromedriver + 4233364
15  chromedriver                        0x0000000104aa85e0 chromedriver + 4294112
16  libsystem_pthread.dylib             0x0000000184d46f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000184d41d34 thread_start + 8

In [276]:
print(len(car_names),len(price),len(description))

22 1 1

In [ ]:
import pandas as pd
df = pd.DataFrame({'Car Name': car_names,'Price':price,'Description':description})
df.head()